version: '3.8'

services:
  backend:
    build:
      context: ../backend-clientes
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - banco-net

  frontend:
    build:
      context: ../mi-proyecto-react
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "5173:80"
    networks:
      - banco-net

networks:
  banco-net:
    driver: bridge
